name: Build workflow
on:
  #push:
   # branches: [ "main" ]
  pull_request:
    branches:
      - "main"

  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Mvn Build
        run: mvn install
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: code checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        run: mvn test

      