name: Build workflow
on:
  push:
    branches: [ "main" ]
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Mvn Build
        run: mvn install
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      